printf "grep '%-5s,' */* \n" A
printf "grep '%-5s,' */* \n" ANAT
printf "grep '%-5s,' */* \n" BBDC
printf "grep '%-5s,' */* \n" DAVA
printf "grep '%-5s,' */* \n" EXLS
printf "grep '%-5s,' */* \n" FIVE
printf "grep '%-5s,' */* \n" HCI
printf "grep '%-5s,' */* \n" IR
printf "grep '%-5s,' */* \n" KAI
printf "grep '%-5s,' */* \n" LIT
printf "grep '%-5s,' */* \n" MXIM
printf "grep '%-5s,' */* \n" NTAP
printf "grep '%-5s,' */* \n" PFF
printf "grep '%-5s,' */* \n" SEE
printf "grep '%-5s,' */* \n" SWAV
printf "grep '%-5s,' */* \n" TRNS
printf "grep '%-5s,' */* \n" TU
printf "grep '%-5s,' */* \n" SEAS
printf "grep '%-5s,' */* \n" ALLE
printf "grep '%-5s,' */* \n" ARW
printf "grep '%-5s,' */* \n" FIBK
printf "grep '%-5s,' */* \n" MHO
printf "grep '%-5s,' */* \n" XLI
printf "grep '%-5s,' */* \n" TTEC
printf "grep '%-5s,' */* \n" SF
printf "grep '%-5s,' */* \n" SDY
printf "grep '%-5s,' */* \n" MLI
printf "grep '%-5s,' */* \n" MAN
printf "grep '%-5s,' */* \n" SLX
printf "grep '%-5s,' */* \n" CMA
printf "grep '%-5s,' */* \n" ACHC
