ch-buy:
	python3 chart/BB.py stock-code-list/buy-list.txt > ../docs/chart/BB.html
	python3 chart/MACD.py stock-code-list/buy-list.txt > ../docs/chart/MACD.html
	python3 chart/IchimokuCloud.py stock-code-list/buy-list.txt > ../docs/chart/IchimokuCloud.html
ch-ichi:
	python3 chart/BB.py stock-code-list/filterIchimoku.txt > ../docs/chart/BB.html
	python3 chart/MACD.py stock-code-list/filterIchimoku.txt > ../docs/chart/MACD.html
	python3 chart/IchimokuCloud.py stock-code-list/filterIchimoku.txt > ../docs/chart/IchimokuCloud.html
ba:
	python3 backtest/MACD.py > backtest/MACD.txt
	python3 backtest/MACD-cross.py > backtest/MACD-cross.txt
