ch:
	python3 chart/BB.py > ../docs/chart/BB.html
	python3 chart/MACD.py > ../docs/chart/MACD.html
	python3 chart/IchimokuCloud.py > ../docs/chart/IchimokuCloud.html
ba:
	python3 backtest/MACD.py > backtest/MACD.txt
	python3 backtest/MACD-cross.py > backtest/MACD-cross.txt
